In [5]:
import numpy as np
import random
import scipy.stats as sps
import cv2

Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [6]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.42793721 0.25978058 0.89365035 ... 0.25753217 0.6474     0.28974526]
 [0.5454762  0.3863923  0.64785679 ... 0.46506688 0.21871992 0.56975762]
 [0.63263702 0.77247133 0.7679787  ... 0.05598773 0.14843947 0.96053427]
 ...
 [0.90608953 0.33011726 0.89065042 ... 0.64928622 0.57855745 0.96957597]
 [0.4604213  0.12307217 0.00744542 ... 0.78225919 0.67922469 0.55848774]
 [0.79040318 0.03291432 0.24790355 ... 0.67608176 0.77484046 0.24069935]]
[[0.12750161 0.65027567 0.16137914 ... 0.99041745 0.86490195 0.6944459 ]
 [0.62637531 0.8391775  0.12842199 ... 0.77463352 0.98125812 0.82392636]
 [0.68315035 0.95650864 0.03414043 ... 0.74740203 0.5090225  0.46040553]
 ...
 [0.94285415 0.96317988 0.47809283 ... 0.98631987 0.21563492 0.88793506]
 [0.79556921 0.04466447 0.30051545 ... 0.87620804 0.25012959 0.13511076]
 [0.86286434 0.9700591  0.4613181  ... 0.93657358 0.16387373 0.22285502]]


Без использования numpy

In [8]:
def mult(a, b):
    rows_A = len(a)
    cols_A = len(a[0])
    rows_B = len(b)
    cols_B = len(b[0])

    if cols_A != rows_B:
      print("Матрицы не могут быть перемножены")
      return

    # Создание результата как нулевой матрицы
    result = [[0 for row in range(cols_B)] for col in range(rows_A)]

    # Перемножение матриц
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += a[i][k] * b[k][j]

    return result

C использованием numpy

In [9]:
def np_mult(a, b):
    return np.matmul(a, b)

In [10]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 1.02 s
Wall time: 1.03 s


In [11]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 19.1 ms


In [12]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.361399881716352e-11

Задание 2
Вам подаются на вход два вектора a и b в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy и без. Засеките время работы, как это показано в заданиях выше.

In [13]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.70259346 0.66990047 0.49892731] [0.91692801 0.82606956 0.26243404]


In [14]:
def scalar_product(a,b):
    if len(a) != len(b):
        raise ValueError("Векторы должны быть одинаковой длины")
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [15]:
def np_scalar_product(a, b):
    return np.dot(a, b)

In [16]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 10 ms


0.0

Почему методы numpy оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

Ответ: numpy эффективнее, чем стандартные методы Python, по следующим причинам:

1. numpy использует оптимизированные операции над массивами, которые реализованы на более низком уровне языка (например, на C или Fortran). Эти операции являются векторизованными, т.е. выполняются без явного использования циклов, что означает, что они обрабатывают целые массивы данных, а не отдельные элементы

2. в numpy массивы хранятся в непрерывных блоках памяти, что улучшает производительность за счет уменьшения накладных расходов на доступ к памяти

3. numpy может выполнять некоторые операции параллельно, что ускоряет обработку данных

Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести 0.

In [17]:
def np_diag_2k(a):
    diag_elements = np.diagonal(a)
    even_elements = diag_elements[diag_elements % 2 == 0]

    if even_elements.size == 0:
        return 0

    return np.sum(even_elements)

In [18]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[9, 8, 9, 3, 5],
       [9, 4, 7, 9, 6],
       [8, 8, 7, 8, 9],
       [1, 8, 5, 1, 8],
       [4, 4, 9, 4, 2]])

In [19]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 10.5 ms


6

Задание 4
На вход дан двумерный массив  X . Напишите функцию, которая для каждой строчки  x=(x1,x2,…,xn)  массива  X  строит строчку  s=(s1,s2,…,sn) , где  sk=x1+...+xkk , а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и  X .

In [20]:
def np_sec_av(*A):
    B = np.cumsum(A, axis=1)
    n = np.arange(1, B.shape[1]+1)
    result = B / n
    return result

In [21]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[7.37919222e-01 6.66777998e-01 3.82989451e-02 2.03987285e-01
 5.37662544e-01 1.59626597e-01 7.25619429e-01 7.48375876e-01
 2.56897533e-01 8.84235958e-01 7.85714386e-01 9.83623057e-01
 9.29613625e-01 5.44040308e-01 8.63975799e-01 2.74868021e-01
 5.15205439e-01 1.28849775e-01 4.43281028e-01 7.81226561e-01
 9.57762503e-01 9.24487330e-01 8.91824861e-02 1.03094761e-01
 1.29624563e-01 3.72948255e-01 1.77837095e-01 8.99412874e-01
 2.39456053e-01 1.47637208e-01 5.03565108e-02 7.56890511e-02
 1.57813137e-01 1.51721578e-01 1.15669075e-01 1.62628641e-01
 4.74298275e-01 5.72808091e-01 6.21231634e-01 5.65941083e-01
 5.10008379e-01 8.59651735e-01 1.16078838e-01 9.87062547e-01
 7.94125673e-01 4.89330013e-02 9.43169007e-01 1.84621164e-01
 2.73771960e-01 9.11158217e-01 3.54920108e-01 9.17725205e-01
 9.58038228e-01 9.14911990e-01 8.84688657e-01 1.52483916e-01
 3.11555493e-01 1.82192403e-02 7.90119474e-01 4.60458866e-01
 1.30175768e-01 8.71342843e-01 8.24454040e-01 5.13255311e-01
 4.72786391e-01 3.802857

Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [22]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    grouped_elements = [(key, len(list(group))) for key, group in groupby(a)]
    elements, counts = zip(*grouped_elements)

    elements_array = np.array(elements)
    counts_array = np.array(counts)

    return elements_array, counts_array

In [25]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: total: 0 ns
Wall time: 1 ms


Задание 6
Пусть задан некоторый одномерный массив  X . Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число  a  (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив  X  при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.

Пример:
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [27]:
def np_transformation(X, a=1):
    """
    param X: array
    """
    Y = np.copy(X)
    Y[1::2] = a
    Y[::2] = Y[::2] ** 3
    Y = Y[::-1]

    result = np.concatenate((X, Y))[::-1]
    return result

In [28]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: total: 0 ns
Wall time: 11 ms
